### ISSUE TITLE
max-size requirement

### ISSUE THREAD

**Issue by xujianrj** [nathancahill/Split.js#122] opened 2018-01-25 01:47 UTC
Just like the minSize option , I need maxSize option for the split.
when the element reach the max size ,the size do not change any more.
Will you please add this option?

**Comment by kgrosvenor** [comment] 2018-02-17 00:26
I agree, it felt natural for me to try that too, but it didn't work

**Comment by nathancahill** [comment] 2018-10-09 03:49
Duplicate of #66.

**Closed by nathancahill** 2018-10-09 03:49 UTC
