### ISSUE TITLE
How to remove/add split panel dynamically ?

### ISSUE THREAD

**Issue by deepaksibar** [nathancahill/Split.js#47] opened 2016-06-17 06:18 UTC
Hi,

In my application there are multiple split panel. So we have to provide feature like user could remove or add any panel dynamically.
So are you supporting this feature right now. If yes, then please let me know how to achieve this.

**Comment by nathancahill** [comment] 2016-07-07 15:24
Duplicate of #27

**Closed by nathancahill** 2016-07-07 15:24 UTC
